label: 'Página inicio'
description: 'Todo el contenido promovido a la página principal.'
display:
  default:
    display_title: 'Por defecto'
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        title:
          title: ¡Bienvenidos!
  feed_1:
    display_title: 'Canal de noticias'
  page_1:
    display_title: Página
