label: '"J''aime"'
display:
  default:
    display_title: 'Par défaut'
    display_options:
      title: '"J''aime"'
      fields:
        id:
          label: 'Identifiant (ID)'
          separator: ', '
        entity_type:
          label: "Type d'entité"
          separator: ', '
        entity_id:
          label: "Identifiant (ID) de l'entité"
          separator: ', '
        uid:
          label: 'Identifiant (ID) utilisateur'
          separator: ', '
        value:
          label: Valeur
          separator: ', '
        operations:
          label: "Liens d'actions"
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
  page_1:
    display_title: Page
    display_options:
      menu:
        title: '"J''aime"'
