label: "Page d'accueil"
description: "Tout le contenu promu en page d'accueil."
display:
  default:
    display_title: 'Par défaut'
    display_options:
      exposed_form:
        options:
          submit_button: Appliquer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        title:
          title: 'Bienvenue !'
  feed_1:
    display_title: Flux
  page_1:
    display_title: Page
