_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: 10
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__3':
    expanded: true
    parent: ''
    weight: 0
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__4':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.3'
    weight: 0
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__8':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.3'
    weight: 1
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__9':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.8'
    weight: 0
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__5':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.3'
    weight: 2
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__7':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.3'
    weight: 3
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__6':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.3'
    weight: 4
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__1':
    expanded: true
    parent: ''
    weight: 7
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__2':
    expanded: true
    parent: ''
    weight: 8
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__10':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.2'
    weight: 0
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__11':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.2'
    weight: 0
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__14':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.2'
    weight: 0
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__13':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.2'
    weight: 0
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__12':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.2'
    weight: 0
    menu_name: leftcategories
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__15':
    expanded: true
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.left_categories.2'
    weight: 0
    menu_name: leftcategories
    enabled: true
  user__logout:
    weight: 11
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: 0
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__left_categories__16':
    enabled: false
    menu_name: leftcategories
    parent: ''
    expanded: true
    weight: 0
