_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bookmarks: 0
  breakpoint: 0
  cache_control_override: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  csv_recipe_import: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  facets: 0
  facets_exposed_filters: 0
  facets_searchbox_widget: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  js_cookie: 0
  language: 0
  like: 0
  link: 0
  locale: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  search_api: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_entity_form_field: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable9: 0
  bootstrap5: 0
  recette: 0
profile: standard
