_core:
  default_config_hash: cGNacasmNogwpTFr99Sbtf6LMiXS8_oZOzhMuI-8doA
enabled_entity_types:
  comment: '0'
  contact_message: '0'
  node: '0'
  block_content: '0'
  menu_link_content: '0'
  file: '0'
  flagging: '0'
  shortcut: '0'
  taxonomy_term: '0'
  path_alias: '0'
  user: '0'
  webform_submission: '0'
like_cookie_expiry_time: 31536000
cache_type: entity
